import type { MetadataRoute } from 'next';

import { siteConfig } from '@/config/site';

/**
 * Dynamic robots.txt
 * Generated by Next.js at /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin/', '/api/', '/auth/', '/account/'],
      },
    ],
    sitemap: `${siteConfig.url}/sitemap.xml`,
  };
}
