import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import collectionsRouter from "./collections";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import customersRouter from "./customers";
import reviewsRouter from "./reviews";
import wishlistRouter from "./wishlist";
import couponsRouter from "./coupons";
import inventoryRouter from "./inventory";
import newsletterRouter from "./newsletter";
import contactRouter from "./contact";
import financeRouter from "./finance";
import expensesRouter from "./expenses";
import employeesRouter from "./employees";
import adSpendsRouter from "./adSpends";
import governoratesRouter from "./governorates";
import storageRouter from "./storage";
import paymentSettingsRouter from "./payment-settings";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(collectionsRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(customersRouter);
router.use(reviewsRouter);
router.use(wishlistRouter);
router.use(couponsRouter);
router.use(inventoryRouter);
router.use(newsletterRouter);
router.use(contactRouter);
router.use(financeRouter);
router.use(expensesRouter);
router.use(employeesRouter);
router.use(adSpendsRouter);
router.use(governoratesRouter);
router.use(storageRouter);
router.use(paymentSettingsRouter);

export default router;
